<?php

namespace ContainerR3FxiNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookControllerbookDetailsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.b3R8WOF.App\Controller\BookController::bookDetails()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.b3R8WOF.App\\Controller\\BookController::bookDetails()'] = ($container->privates['.service_locator.b3R8WOF'] ?? $container->load('get_ServiceLocator_B3R8WOFService'))->withContext('App\\Controller\\BookController::bookDetails()', $container);
    }
}
