<?php

namespace ContainerR3FxiNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookControllereditBookService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RtAZSfs.App\Controller\BookController::editBook()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RtAZSfs.App\\Controller\\BookController::editBook()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'book' => ['privates', '.errored..service_locator.RtAZSfs.App\\Entity\\Book', NULL, 'Cannot autowire service ".service_locator.RtAZSfs": it needs an instance of "App\\Entity\\Book" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'formFactory' => ['privates', 'form.factory', 'getForm_FactoryService', true],
        ], [
            'book' => 'App\\Entity\\Book',
            'em' => '?',
            'formFactory' => '?',
        ]))->withContext('App\\Controller\\BookController::editBook()', $container);
    }
}
