<?php

namespace ContainerR3FxiNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBooksControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Jjt.sz..App\Controller\API\BooksController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Jjt.sz..App\\Controller\\API\\BooksController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\BookRepository', 'getBookRepositoryService', true],
            'paginationDTO' => ['privates', 'App\\DTO\\PaginationDTO', 'getPaginationDTOService', true],
        ], [
            'repository' => 'App\\Repository\\BookRepository',
            'paginationDTO' => 'App\\DTO\\PaginationDTO',
        ]))->withContext('App\\Controller\\API\\BooksController::index()', $container);
    }
}
