<?php

namespace ContainerR3FxiNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaginationDTOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\DTO\PaginationDTO' shared autowired service.
     *
     * @return \App\DTO\PaginationDTO
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'DTO'.\DIRECTORY_SEPARATOR.'PaginationDTO.php';

        return $container->privates['App\\DTO\\PaginationDTO'] = new \App\DTO\PaginationDTO();
    }
}
