vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        cars:
            uri_prefix: /images/cars
            upload_destination: '%kernel.project_dir%/public/images/cars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true


        profilePic:
            uri_prefix: /images/profilePics
            upload_destination: '%kernel.project_dir%/public/images/profilePics'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer