<?php

namespace ContainerDPRkp9E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I2nyvKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._i2nyvK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._i2nyvK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\BookController::index' => ['privates', '.service_locator.F4lmtQl.App\\Controller\\BookController::index()', 'getBookControllerindexService', true],
            'App\\Controller\\BookController::create' => ['privates', '.service_locator.irhSf4a.App\\Controller\\BookController::create()', 'getBookControllercreateService', true],
            'App\\Controller\\BookController::bookDetails' => ['privates', '.service_locator.b3R8WOF.App\\Controller\\BookController::bookDetails()', 'getBookControllerbookDetailsService', true],
            'App\\Controller\\BookController::editBook' => ['privates', '.service_locator.RtAZSfs.App\\Controller\\BookController::editBook()', 'getBookControllereditBookService', true],
            'App\\Controller\\BookController::removeBook' => ['privates', '.service_locator.6VUlBFg.App\\Controller\\BookController::removeBook()', 'getBookControllerremoveBookService', true],
            'App\\Controller\\CommentController::driverProfile' => ['privates', '.service_locator.VgO1BMn.App\\Controller\\CommentController::driverProfile()', 'getCommentControllerdriverProfileService', true],
            'App\\Controller\\CommentController::edit' => ['privates', '.service_locator.yAff5wu.App\\Controller\\CommentController::edit()', 'getCommentControllereditService', true],
            'App\\Controller\\ContactController::contact' => ['privates', '.service_locator.HKv6Vyy.App\\Controller\\ContactController::contact()', 'getContactControllercontactService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.tEL1pRK.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\RegistrationController::verifyUserEmail' => ['privates', '.service_locator.KHhLDTq.App\\Controller\\RegistrationController::verifyUserEmail()', 'getRegistrationControllerverifyUserEmailService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\BookController:index' => ['privates', '.service_locator.F4lmtQl.App\\Controller\\BookController::index()', 'getBookControllerindexService', true],
            'App\\Controller\\BookController:create' => ['privates', '.service_locator.irhSf4a.App\\Controller\\BookController::create()', 'getBookControllercreateService', true],
            'App\\Controller\\BookController:bookDetails' => ['privates', '.service_locator.b3R8WOF.App\\Controller\\BookController::bookDetails()', 'getBookControllerbookDetailsService', true],
            'App\\Controller\\BookController:editBook' => ['privates', '.service_locator.RtAZSfs.App\\Controller\\BookController::editBook()', 'getBookControllereditBookService', true],
            'App\\Controller\\BookController:removeBook' => ['privates', '.service_locator.6VUlBFg.App\\Controller\\BookController::removeBook()', 'getBookControllerremoveBookService', true],
            'App\\Controller\\CommentController:driverProfile' => ['privates', '.service_locator.VgO1BMn.App\\Controller\\CommentController::driverProfile()', 'getCommentControllerdriverProfileService', true],
            'App\\Controller\\CommentController:edit' => ['privates', '.service_locator.yAff5wu.App\\Controller\\CommentController::edit()', 'getCommentControllereditService', true],
            'App\\Controller\\ContactController:contact' => ['privates', '.service_locator.HKv6Vyy.App\\Controller\\ContactController::contact()', 'getContactControllercontactService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.tEL1pRK.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\RegistrationController:verifyUserEmail' => ['privates', '.service_locator.KHhLDTq.App\\Controller\\RegistrationController::verifyUserEmail()', 'getRegistrationControllerverifyUserEmailService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\BookController::index' => '?',
            'App\\Controller\\BookController::create' => '?',
            'App\\Controller\\BookController::bookDetails' => '?',
            'App\\Controller\\BookController::editBook' => '?',
            'App\\Controller\\BookController::removeBook' => '?',
            'App\\Controller\\CommentController::driverProfile' => '?',
            'App\\Controller\\CommentController::edit' => '?',
            'App\\Controller\\ContactController::contact' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::verifyUserEmail' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\BookController:index' => '?',
            'App\\Controller\\BookController:create' => '?',
            'App\\Controller\\BookController:bookDetails' => '?',
            'App\\Controller\\BookController:editBook' => '?',
            'App\\Controller\\BookController:removeBook' => '?',
            'App\\Controller\\CommentController:driverProfile' => '?',
            'App\\Controller\\CommentController:edit' => '?',
            'App\\Controller\\ContactController:contact' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:verifyUserEmail' => '?',
            'App\\Controller\\SecurityController:login' => '?',
        ]);
    }
}
