<?php

namespace ContainerDPRkp9E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.irhSf4a.App\Controller\BookController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.irhSf4a.App\\Controller\\BookController::create()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'formFactory' => ['privates', 'form.factory', 'getForm_FactoryService', true],
        ], [
            'em' => '?',
            'formFactory' => '?',
        ]))->withContext('App\\Controller\\BookController::create()', $container);
    }
}
