<?php

namespace ContainerDPRkp9E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookControllerremoveBookService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6VUlBFg.App\Controller\BookController::removeBook()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6VUlBFg.App\\Controller\\BookController::removeBook()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'book' => ['privates', '.errored..service_locator.6VUlBFg.App\\Entity\\Book', NULL, 'Cannot autowire service ".service_locator.6VUlBFg": it needs an instance of "App\\Entity\\Book" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'book' => 'App\\Entity\\Book',
            'em' => '?',
        ]))->withContext('App\\Controller\\BookController::removeBook()', $container);
    }
}
