<?php

namespace ContainerDPRkp9E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentControllerdriverProfileService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VgO1BMn.App\Controller\CommentController::driverProfile()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VgO1BMn.App\\Controller\\CommentController::driverProfile()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
            'formFactory' => ['privates', 'form.factory', 'getForm_FactoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'repository' => 'App\\Repository\\CommentRepository',
            'security' => '?',
            'formFactory' => '?',
            'em' => '?',
        ]))->withContext('App\\Controller\\CommentController::driverProfile()', $container);
    }
}
