<?php

namespace ContainerDPRkp9E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yAff5wu.App\Controller\CommentController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yAff5wu.App\\Controller\\CommentController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'comment' => ['privates', '.errored..service_locator.yAff5wu.App\\Entity\\Comment', NULL, 'Cannot autowire service ".service_locator.yAff5wu": it needs an instance of "App\\Entity\\Comment" but this type has been excluded because it\'s a Doctrine entity.'],
            'en' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'comment' => 'App\\Entity\\Comment',
            'en' => '?',
        ]))->withContext('App\\Controller\\CommentController::edit()', $container);
    }
}
